changelog and readme renewal, toward Oct 1 Update
OpenTTD-China-Set/China-Set-Trains pull request #79
Opened 2024-09-30 21:16 UTC by JohnFranklin523

2024-09-30 21:30 UTC, WenSimEHRP requested changes

2024-09-30 21:30 UTC, WenSimEHRP commented on README.md
> -China Set: Trains is the train sector of the China set of OpenTTD.\
Better keep that line break

2024-09-30 21:30 UTC, WenSimEHRP commented on README.md
> +| Cargo age period<br />for freight wagons                           | Change the rate cargo in mail and freight wagons<br />gets aged; independent from the parameter above
Html?

2024-09-30 21:30 UTC, WenSimEHRP commented on README.md
> +Using Linux or WSL:#!/bin/bash
Typo? Shebang shouldn't be here

2024-09-30 21:30 UTC, WenSimEHRP commented on README.md
> +- dP
Alphabetical order, d is before e

2024-10-01 07:46 UTC, JohnFranklin523 commented on README.md
> +- dP
okay

2024-10-01 07:46 UTC, jfkuayue commented on README.md
> +| Cargo age period<br />for freight wagons                           | Change the rate cargo in mail and freight wagons<br />gets aged; independent from the parameter above
yes

2024-10-01 07:51 UTC, WenSimEHRP commented on README.md
> +| Cargo age period<br />for freight wagons                           | Change the rate cargo in mail and freight wagons<br />gets aged; independent from the parameter above
remove it then. Make it a footnote or whatever thing that is markdown native.

2024-10-01 07:52 UTC, WenSimEHRP commented on README.md
> +- dP
better force push by the way; don't let the minor changes spam the commit history

2024-10-01 10:02 UTC, merged

2024-10-01 16:00 UTC, wensimehrp commented
gosh you squashed many changes in one commit

2024-10-20 21:46 UTC, WenSimEHRP commented on README.md
> +- peter1138
I feel like you're just listing whatever people you've talked with :-1:

2024-10-20 22:06 UTC, JohnFranklin523 commented on README.md
> +- peter1138
?

2024-10-20 22:08 UTC, JohnFranklin523 commented on README.md
> +- peter1138
No, Peter had a PR that solved extra speed for non-tilt high speed trains at sharp turns.

2024-10-20 22:10 UTC, WenSimEHRP commented on README.md
> +- peter1138
whatever